spring.application.name=EcommerceBackend

# Whenever deploy this on any server like render/railway/aws set following env vars there
# DB_UL
# DB_USERNAME
# DB_PASSWORD
# SPRING_PROFILES_ACTIVE=prod    -> This profile will redirect the configs to application-prod.properties

# Datasource (from environment variables)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Production-safe JPA settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Optional but recommended
spring.jpa.properties.hibernate.format_sql=false

# Logging (less noisy)
logging.level.org.springframework=WARN