spring.application.name=EcommerceBackend

# This is to change the profile to be use i.e.
# profile = application-[profile].properties
# if not provided it remains default and uses application.properties
# local = it uses application-local.properties
# prod = it uses application-prod.properties

spring.profiles.active=local
